//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp
{
    using System;


    public partial class Included : global::Microsoft.VisualStudio.TextTemplating.TextTransformation
    {


#line 7 "/Users/yangjiefeng/GitHub/T4-DirectiveProcessor-Example/Included.tt"

        public static class Hello
        {
            public static string sayHello()
            {
                return "Hello, world!";
            }
        }

#line default
#line hidden


        public override string TransformText()
        {
            this.GenerationEnvironment = null;
            return this.GenerationEnvironment.ToString();
        }

        public override void Initialize()
        {
            base.Initialize();
        }
    }
}
